In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("cardio_cleaned.csv")

df.shape

(68751, 12)

In [2]:
df.sample(1)

,age_years,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
19440,49.837098,1,165,65.0,120,80,1,1,0,0,1,0

In [3]:
X = df.drop('cardio', axis=1)
y = df['cardio']

In [4]:
print(X.shape)
print(y.shape)
print(X.head())
print(y.head())

(68751, 11)
(68751,)
   age_years  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  50.357290       2     168    62.0    110     80            1     1      0
1  55.381246       1     156    85.0    140     90            3     1      0
2  51.627652       1     165    64.0    130     70            3     1      0
3  48.249144       2     169    82.0    150    100            1     1      0
4  47.841205       1     156    56.0    100     60            1     1      0

   alco  active
0     0       1
1     0       1
2     0       0
3     0       1
4     0       0
0    0
1    1
2    1
3    1
4    0
Name: cardio, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [6]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((55000, 11), (13751, 11), (55000,), (13751,))

In [7]:
df.head()

,age_years,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50.357290,2,168,62.0,110,80,1,1,0,0,1,0
1,55.381246,1,156,85.0,140,90,3,1,0,0,1,1
2,51.627652,1,165,64.0,130,70,3,1,0,0,0,1
3,48.249144,2,169,82.0,150,100,1,1,0,0,1,1
4,47.841205,1,156,56.0,100,60,1,1,0,0,0,0

In [8]:
print(X.columns.tolist())

['age_years', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [10]:
numeric_features = [
    'age_years',
    'height',
    'weight',
    'ap_hi',
    'ap_lo'
]

categorical_features = [
    'gender',
    'cholesterol',
    'gluc',
    'smoke',
    'alco',
    'active'
]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

In [11]:
logistic_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', LogisticRegression(max_iter=1000))
    ]
)

In [12]:
logistic_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age_years', 'height',
                                                   'weight', 'ap_hi',
                                                   'ap_lo']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'cholesterol',
                                                   'gluc', 'smoke', 'alco',
                                                   'active'])])),
                ('model', LogisticRegression(max_iter=1000))])

In [23]:
y_prob = logistic_pipeline.predict_proba(X_test)[:, 1]

In [24]:
y_pred = logistic_pipeline.predict(X_test)

In [25]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.7259835648316486
Precision: 0.7528295605858855
Recall   : 0.6645606817513958
F1 Score : 0.7059466208834088
ROC-AUC  : 0.7893266052674057

In [26]:
results = []

results.append({
    'Model': 'Logistic Regression',
    'Accuracy': accuracy_score(y_test, y_pred),
    'Precision': precision_score(y_test, y_pred),
    'Recall': recall_score(y_test, y_pred),
    'F1': f1_score(y_test, y_pred),
    'ROC-AUC': roc_auc_score(y_test, y_prob)
})

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
dt_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', DecisionTreeClassifier(random_state=42))
    ]
)

In [29]:
dt_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age_years', 'height',
                                                   'weight', 'ap_hi',
                                                   'ap_lo']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'cholesterol',
                                                   'gluc', 'smoke', 'alco',
                                                   'active'])])),
                ('model', DecisionTreeClassifier(random_state=42))])

In [30]:
y_pred_dt = dt_pipeline.predict(X_test)
y_prob_dt = dt_pipeline.predict_proba(X_test)[:, 1]

In [31]:
print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_dt))

Accuracy : 0.6296996582066758
Precision: 0.626925355450237
Recall   : 0.6219512195121951
F1 Score : 0.6244283817672223
ROC-AUC  : 0.6295132486962018

In [32]:
results.append({
    'Model': 'Decision Tree',
    'Accuracy': accuracy_score(y_test, y_pred_dt),
    'Precision': precision_score(y_test, y_pred_dt),
    'Recall': recall_score(y_test, y_pred_dt),
    'F1': f1_score(y_test, y_pred_dt),
    'ROC-AUC': roc_auc_score(y_test, y_prob_dt)
})

In [33]:
from sklearn.model_selection import GridSearchCV

In [34]:
dt_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', DecisionTreeClassifier(random_state=42))
    ]
)

In [35]:
param_grid = {
    'model__max_depth': [3, 5, 7, 10, 15, None],
    'model__min_samples_split': [2, 5, 10],
    'model__min_samples_leaf': [1, 2, 5, 10]
}

In [36]:
grid_search_dt = GridSearchCV(
    estimator=dt_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

In [37]:
grid_search_dt.fit(X_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['age_years',
                                                                          'height',
                                                                          'weight',
                                                                          'ap_hi',
                                                                          'ap_lo']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'cholesterol',
                                                                          'gluc',
                                                                          'smoke',
                                                                          'alco',
                                                                          'active'])])),
                                       ('model',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [3, 5, 7, 10, 15, None],
                         'model__min_samples_leaf': [1, 2, 5, 10],
                         'model__min_samples_split': [2, 5, 10]},
             scoring='f1', verbose=1)

In [38]:
print("Best Parameters:")
print(grid_search_dt.best_params_)

Best Parameters:
{'model__max_depth': 7, 'model__min_samples_leaf': 5, 'model__min_samples_split': 2}

In [39]:
y_pred_dt_tuned = grid_search_dt.predict(X_test)
y_prob_dt_tuned = grid_search_dt.predict_proba(X_test)[:, 1]

In [40]:
print("Accuracy :", accuracy_score(y_test, y_pred_dt_tuned))
print("Precision:", precision_score(y_test, y_pred_dt_tuned))
print("Recall   :", recall_score(y_test, y_pred_dt_tuned))
print("F1 Score :", f1_score(y_test, y_pred_dt_tuned))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_dt_tuned))

Accuracy : 0.7262017307832158
Precision: 0.7487322100441681
Recall   : 0.6724948574786953
F1 Score : 0.7085687746729623
ROC-AUC  : 0.7918894881004289

In [41]:
results.append({
    'Model': 'Decision Tree Tuned',
    'Accuracy': accuracy_score(y_test, y_pred_dt_tuned),
    'Precision': precision_score(y_test, y_pred_dt_tuned),
    'Recall': recall_score(y_test, y_pred_dt_tuned),
    'F1': f1_score(y_test, y_pred_dt_tuned),
    'ROC-AUC': roc_auc_score(y_test, y_prob_dt_tuned)
})

In [42]:
pd.DataFrame(results)

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.725984   0.752830  0.664561  0.705947  0.789327
1        Decision Tree  0.629700   0.626925  0.621951  0.624428  0.629513
2  Decision Tree Tuned  0.726202   0.748732  0.672495  0.708569  0.791889

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
rf_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', RandomForestClassifier(random_state=42))
    ]
)

In [45]:
rf_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age_years', 'height',
                                                   'weight', 'ap_hi',
                                                   'ap_lo']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'cholesterol',
                                                   'gluc', 'smoke', 'alco',
                                                   'active'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [46]:
y_pred_rf = rf_pipeline.predict(X_test)
y_prob_rf = rf_pipeline.predict_proba(X_test)[:, 1]

In [47]:
print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1 Score :", f1_score(y_test, y_pred_rf))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_rf))

Accuracy : 0.7078757908515745
Precision: 0.7094787441790597
Recall   : 0.6939465177784307
F1 Score : 0.701626680531828
ROC-AUC  : 0.7722834867891732

In [52]:
results.append({
    'Model': 'Random Forest',
    'Accuracy': accuracy_score(y_test, y_pred_rf),
    'Precision': precision_score(y_test, y_pred_rf),
    'Recall': recall_score(y_test, y_pred_rf),
    'F1': f1_score(y_test, y_pred_rf),
    'ROC-AUC': roc_auc_score(y_test, y_prob_rf)
})

In [48]:
rf_param_grid = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [5, 10, 15],
    'model__min_samples_split': [2, 5],
    'model__min_samples_leaf': [1, 2]
}

In [49]:
grid_search_rf = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=rf_param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

In [50]:
grid_search_rf.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['age_years',
                                                                          'height',
                                                                          'weight',
                                                                          'ap_hi',
                                                                          'ap_lo']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'cholesterol',
                                                                          'gluc',
                                                                          'smoke',
                                                                          'alco',
                                                                          'active'])])),
                                       ('model',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [5, 10, 15],
                         'model__min_samples_leaf': [1, 2],
                         'model__min_samples_split': [2, 5],
                         'model__n_estimators': [100, 200]},
             scoring='f1', verbose=1)

In [51]:
print("Best Parameters:")
print(grid_search_rf.best_params_)

print("Best CV F1:")
print(grid_search_rf.best_score_)

Best Parameters:
{'model__max_depth': 15, 'model__min_samples_leaf': 2, 'model__min_samples_split': 2, 'model__n_estimators': 200}
Best CV F1:
0.7185898816492357

In [53]:
y_pred_rf_tuned = grid_search_rf.predict(X_test)

y_prob_rf_tuned = grid_search_rf.predict_proba(X_test)[:, 1]

In [54]:
print("Accuracy :", accuracy_score(y_test, y_pred_rf_tuned))
print("Precision:", precision_score(y_test, y_pred_rf_tuned))
print("Recall   :", recall_score(y_test, y_pred_rf_tuned))
print("F1 Score :", f1_score(y_test, y_pred_rf_tuned))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_rf_tuned))

Accuracy : 0.7299105519598574
Precision: 0.7506485084306096
Recall   : 0.6802821040258595
F1 Score : 0.7137351626329582
ROC-AUC  : 0.7980574142960717

In [55]:
results.append({
    'Model': 'Random Forest Tuned',
    'Accuracy': accuracy_score(y_test, y_pred_rf_tuned),
    'Precision': precision_score(y_test, y_pred_rf_tuned),
    'Recall': recall_score(y_test, y_pred_rf_tuned),
    'F1': f1_score(y_test, y_pred_rf_tuned),
    'ROC-AUC': roc_auc_score(y_test, y_prob_rf_tuned)
})

In [56]:
pd.DataFrame(results)

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.725984   0.752830  0.664561  0.705947  0.789327
1        Decision Tree  0.629700   0.626925  0.621951  0.624428  0.629513
2  Decision Tree Tuned  0.726202   0.748732  0.672495  0.708569  0.791889
3        Random Forest  0.707876   0.709479  0.693947  0.701627  0.772283
4  Random Forest Tuned  0.729911   0.750649  0.680282  0.713735  0.798057

In [57]:
from sklearn.ensemble import GradientBoostingClassifier

In [58]:
gb_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', GradientBoostingClassifier(random_state=42))
    ]
)

In [59]:
gb_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age_years', 'height',
                                                   'weight', 'ap_hi',
                                                   'ap_lo']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'cholesterol',
                                                   'gluc', 'smoke', 'alco',
                                                   'active'])])),
                ('model', GradientBoostingClassifier(random_state=42))])

In [60]:
y_pred_gb = gb_pipeline.predict(X_test)
y_prob_gb = gb_pipeline.predict_proba(X_test)[:, 1]

In [61]:
print("Accuracy :", accuracy_score(y_test, y_pred_gb))
print("Precision:", precision_score(y_test, y_pred_gb))
print("Recall   :", recall_score(y_test, y_pred_gb))
print("F1 Score :", f1_score(y_test, y_pred_gb))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_gb))

Accuracy : 0.7323103774270963
Precision: 0.751246181058048
Recall   : 0.6864531295915369
F1 Score : 0.7173896353166986
ROC-AUC  : 0.8009902328589499

In [62]:
results.append({
    'Model': 'Gradient Boosting',
    'Accuracy': accuracy_score(y_test, y_pred_gb),
    'Precision': precision_score(y_test, y_pred_gb),
    'Recall': recall_score(y_test, y_pred_gb),
    'F1': f1_score(y_test, y_pred_gb),
    'ROC-AUC': roc_auc_score(y_test, y_prob_gb)
})

In [63]:
gb_param_grid = {
    'model__n_estimators': [100, 150, 200],
    'model__learning_rate': [0.05, 0.1],
    'model__max_depth': [2, 3, 4],
    'model__min_samples_leaf': [1, 2, 5]
}

In [64]:
grid_search_gb = GridSearchCV(
    estimator=gb_pipeline,
    param_grid=gb_param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

In [65]:
grid_search_gb.fit(X_train, y_train)

Fitting 5 folds for each of 54 candidates, totalling 270 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['age_years',
                                                                          'height',
                                                                          'weight',
                                                                          'ap_hi',
                                                                          'ap_lo']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'cholesterol',
                                                                          'gluc',
                                                                          'smoke',
                                                                          'alco',
                                                                          'active'])])),
                                       ('model',
                                        GradientBoostingClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1],
                         'model__max_depth': [2, 3, 4],
                         'model__min_samples_leaf': [1, 2, 5],
                         'model__n_estimators': [100, 150, 200]},
             scoring='f1', verbose=1)

In [ ]:
print("Best Parameters:")
print(grid_search_gb.best_params_)

print("Best CV F1:")
print(grid_search_gb.best_score_)

Best Parameters:
{'model__learning_rate': 0.1, 'model__max_depth': 3, 'model__min_samples_leaf': 1, 'model__n_estimators': 200}
Best CV F1:
0.7212169626972791

In [67]:
y_pred_gb_tuned = grid_search_gb.predict(X_test)

y_prob_gb_tuned = grid_search_gb.predict_proba(X_test)[:, 1]

In [68]:
print("Accuracy :", accuracy_score(y_test, y_pred_gb_tuned))
print("Precision:", precision_score(y_test, y_pred_gb_tuned))
print("Recall   :", recall_score(y_test, y_pred_gb_tuned))
print("F1 Score :", f1_score(y_test, y_pred_gb_tuned))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_gb_tuned))

Accuracy : 0.7322376554432405
Precision: 0.7487261146496815
Recall   : 0.6908610049955921
F1 Score : 0.7186305975852055
ROC-AUC  : 0.8009600113565996

In [69]:
results.append({
    'Model': 'Gradient Boosting Tuned',
    'Accuracy': accuracy_score(y_test, y_pred_gb_tuned),
    'Precision': precision_score(y_test, y_pred_gb_tuned),
    'Recall': recall_score(y_test, y_pred_gb_tuned),
    'F1': f1_score(y_test, y_pred_gb_tuned),
    'ROC-AUC': roc_auc_score(y_test, y_prob_gb_tuned)
})

In [70]:
from xgboost import XGBClassifier

In [71]:
xgb_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', XGBClassifier(
            random_state=42,
            eval_metric='logloss'
        ))
    ]
)

In [72]:
import time

start_time = time.time()

xgb_pipeline.fit(X_train, y_train)

end_time = time.time()

training_time = end_time - start_time

print(f"Training time: {training_time:.2f} seconds")
print(f"Training time: {training_time/60:.2f} minutes")

Training time: 0.83 seconds
Training time: 0.01 minutes

In [73]:
y_pred_xgb = xgb_pipeline.predict(X_test)

y_prob_xgb = xgb_pipeline.predict_proba(X_test)[:, 1]

In [83]:
results.append({
    'Model': 'XGBoost',
    'Accuracy': accuracy_score(y_test, y_pred_xgb),
    'Precision': precision_score(y_test, y_pred_xgb),
    'Recall': recall_score(y_test, y_pred_xgb),
    'F1': f1_score(y_test, y_pred_xgb),
    'ROC-AUC': roc_auc_score(y_test, y_prob_xgb)
})

In [74]:
print("Accuracy :", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall   :", recall_score(y_test, y_pred_xgb))
print("F1 Score :", f1_score(y_test, y_pred_xgb))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_xgb))

Accuracy : 0.7273652825249073
Precision: 0.7460164171897634
Recall   : 0.6810167499265354
F1 Score : 0.7120362547046624
ROC-AUC  : 0.7930740292466288

In [75]:
xgb_param_grid = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [3, 5],
    'model__learning_rate': [0.05, 0.1],
    'model__subsample': [0.8, 1.0]
}

In [76]:
grid_search_xgb = GridSearchCV(
    estimator=xgb_pipeline,
    param_grid=xgb_param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

In [77]:
grid_search_xgb.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['age_years',
                                                                          'height',
                                                                          'weight',
                                                                          'ap_hi',
                                                                          'ap_lo']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'cholesterol',
                                                                          'gluc',
                                                                          'smoke',
                                                                          'alco',
                                                                          'active'])])),
                                       ('model',
                                        XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_by...
                                                      max_delta_step=None,
                                                      max_depth=None,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1],
                         'model__max_depth': [3, 5],
                         'model__n_estimators': [100, 200],
                         'model__subsample': [0.8, 1.0]},
             scoring='f1', verbose=1)

In [78]:
print("Best Parameters:")
print(grid_search_xgb.best_params_)

print("Best CV F1:")
print(grid_search_xgb.best_score_)

Best Parameters:
{'model__learning_rate': 0.1, 'model__max_depth': 3, 'model__n_estimators': 200, 'model__subsample': 0.8}
Best CV F1:
0.7214564990499484

In [79]:
y_pred_xgb_tuned = grid_search_xgb.predict(X_test)

y_prob_xgb_tuned = grid_search_xgb.predict_proba(X_test)[:, 1]

In [80]:
print("Accuracy :", accuracy_score(y_test, y_pred_xgb_tuned))
print("Precision:", precision_score(y_test, y_pred_xgb_tuned))
print("Recall   :", recall_score(y_test, y_pred_xgb_tuned))
print("F1 Score :", f1_score(y_test, y_pred_xgb_tuned))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_xgb_tuned))

Accuracy : 0.7323830994109519
Precision: 0.7529944966008417
Recall   : 0.6835145459888334
F1 Score : 0.7165742452248922
ROC-AUC  : 0.8010658871063456

In [81]:
results.append({
    'Model': 'XGBoost Tuned',
    'Accuracy': accuracy_score(y_test, y_pred_xgb_tuned),
    'Precision': precision_score(y_test, y_pred_xgb_tuned),
    'Recall': recall_score(y_test, y_pred_xgb_tuned),
    'F1': f1_score(y_test, y_pred_xgb_tuned),
    'ROC-AUC': roc_auc_score(y_test, y_prob_xgb_tuned)
})

In [84]:
pd.DataFrame(results)

                     Model  Accuracy  Precision    Recall        F1   ROC-AUC
0      Logistic Regression  0.725984   0.752830  0.664561  0.705947  0.789327
1            Decision Tree  0.629700   0.626925  0.621951  0.624428  0.629513
2      Decision Tree Tuned  0.726202   0.748732  0.672495  0.708569  0.791889
3            Random Forest  0.707876   0.709479  0.693947  0.701627  0.772283
4      Random Forest Tuned  0.729911   0.750649  0.680282  0.713735  0.798057
5        Gradient Boosting  0.732310   0.751246  0.686453  0.717390  0.800990
6  Gradient Boosting Tuned  0.732238   0.748726  0.690861  0.718631  0.800960
7            XGBoost Tuned  0.732383   0.752994  0.683515  0.716574  0.801066
8                  XGBoost  0.727365   0.746016  0.681017  0.712036  0.793074

In [85]:
results_df = pd.DataFrame(results)

results_df['Final Score'] = (
    0.10 * results_df['Accuracy'] +
    0.15 * results_df['Precision'] +
    0.30 * results_df['Recall'] +
    0.30 * results_df['F1'] +
    0.15 * results_df['ROC-AUC']
)

results_df.sort_values('Final Score', ascending=False)

,Model,Accuracy,Precision,Recall,F1,ROC-AUC,Final Score
6,Gradient Boosting Tuned,0.732238,0.748726,0.690861,0.718631,0.800960,0.728524
5,Gradient Boosting,0.732310,0.751246,0.686453,0.717390,0.800990,0.727219
7,XGBoost Tuned,0.732383,0.752994,0.683515,0.716574,0.801066,0.726374
4,Random Forest Tuned,0.729911,0.750649,0.680282,0.713735,0.798057,0.723502
8,XGBoost,0.727365,0.746016,0.681017,0.712036,0.793074,0.721516
2,Decision Tree Tuned,0.726202,0.748732,0.672495,0.708569,0.791889,0.718033
0,Logistic Regression,0.725984,0.752830,0.664561,0.705947,0.789327,0.715074
3,Random Forest,0.707876,0.709479,0.693947,0.701627,0.772283,0.711724
1,Decision Tree,0.629700,0.626925,0.621951,0.624428,0.629513,0.625350

<h3>Final Model Selection</h3>

<p><strong>Selected Model: Tuned Gradient Boosting</strong></p>

<p>To select the final model, multiple evaluation metrics were considered instead of relying only on accuracy. Since this is a cardiovascular disease prediction problem, greater importance was given to Recall and F1-score because reducing false-negative predictions is important.</p>

<p>A weighted scoring formula was used:</p>

<p><strong>Final Score = 0.10 × Accuracy + 0.15 × Precision + 0.30 × Recall + 0.30 × F1 + 0.15 × ROC-AUC</strong></p>

<p>Using this formula, <strong>Tuned Gradient Boosting achieved the highest Final Score of 0.728524</strong>, outperforming all other evaluated models.</p>

<p>It also achieved the highest F1-score of <strong>0.718631</strong> and the highest Recall of <strong>0.690861</strong>. Although Tuned XGBoost achieved a slightly higher ROC-AUC of 0.801066, the difference was very small, while its F1-score and Recall were lower.</p>

<p>Therefore, <strong>Tuned Gradient Boosting was selected as the final model</strong> because it provides the best overall balance of Accuracy, Precision, Recall, F1-score, and ROC-AUC according to the defined weighted evaluation criteria.</p>

In [86]:
final_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', GradientBoostingClassifier(
            learning_rate=0.1,
            max_depth=3,
            min_samples_leaf=1,
            n_estimators=200,
            random_state=42
        ))
    ]
)

In [87]:
final_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age_years', 'height',
                                                   'weight', 'ap_hi',
                                                   'ap_lo']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'cholesterol',
                                                   'gluc', 'smoke', 'alco',
                                                   'active'])])),
                ('model',
                 GradientBoostingClassifier(n_estimators=200,
                                            random_state=42))])

In [88]:
y_pred_final = final_pipeline.predict(X_test)
y_prob_final = final_pipeline.predict_proba(X_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred_final))
print("Precision:", precision_score(y_test, y_pred_final))
print("Recall   :", recall_score(y_test, y_pred_final))
print("F1 Score :", f1_score(y_test, y_pred_final))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_final))

Accuracy : 0.7322376554432405
Precision: 0.7487261146496815
Recall   : 0.6908610049955921
F1 Score : 0.7186305975852055
ROC-AUC  : 0.8009600113565996

In [89]:
import joblib

joblib.dump(
    final_pipeline,
    "cardiovascular_final_pipeline.pkl"
)

['cardiovascular_final_pipeline.pkl']

In [90]:
import os

print(os.path.getsize("cardiovascular_final_pipeline.pkl"))

270308